### ISSUE TITLE
Units Search

### ISSUE THREAD

**Issue by SoftMilkBread** [sadellie/unitto#11]
It would be easier if we can search units by its symbols, e.g. kg, km, lb.

**Comment by sadellie** [comment]
Done.

Note: In order to search unit by symbol you need to enter it's full short name, i.e. `km` not just letter `k`.
Note 2: **Unitto** sorts units by usage, then sorts by matching strings. _Minor typos are allowed_, btw. You can type `kelometer pir haur` and the app will find `kilometer per hour`.

![image](https://user-images.githubusercontent.com/10384356/210133664-130d33e7-dff5-4ef3-83b9-1b8c57d207e5.png)
