### ISSUE TITLE
Some idea to add

### ISSUE THREAD

**Issue by xmha97** [sadellie/unitto#114]
https://play.google.com/store/apps/details?id=com.veewalabs.unitconverter

![Screenshot_2023-10-31-00-05-28-169_com.veewalabs.unitconverter.jpg](https://github.com/sadellie/unitto/assets/23485114/a34066d9-3137-4ccc-adb7-38dc3faf03a7)

![Screenshot_2023-10-31-00-05-17-664_com.veewalabs.unitconverter.jpg](https://github.com/sadellie/unitto/assets/23485114/9fb28d27-d22c-4777-b094-6ee9bdb920e2)

![Screenshot_2023-10-31-00-05-08-445_com.veewalabs.unitconverter.jpg](https://github.com/sadellie/unitto/assets/23485114/8ae64321-41ed-4684-a203-a756a672820b)

![Screenshot_2023-10-31-00-04-55-755_com.veewalabs.unitconverter.jpg](https://github.com/sadellie/unitto/assets/23485114/9ab9b6a6-9d5f-430e-bc69-a0ab308e01c5)

**Comment by VasilisKos** [comment]
The tax and the discount features are useless, because it's very simple to calculate them with the calculator. What would be nice though to be added is the calculation of the percentage of the tax or the discount, by inputting the initial and final values and get the percentage by just one tapping. This is more complicated to do using the calculator.
The date difference is already included. BMI would be a nice feature.

**Comment by sadellie** [comment]
1. **Sales tax**. Don't see the need for a separate tool here. Calculator allows adding/subtracting percentages.
2. **Discount**. Same thing.
3. **Date difference**. Already implemented (subjectively better)
4. **BMI**. Maybe, created a separate issue and added to the backlog #134
