### ISSUE TITLE
feedback after testing the "quick silver" version (preview)

### ISSUE THREAD

**Issue by Ananas-Kuchen** [sadellie/unitto#168]
[https://github.com/sadellie/unitto/releases/tag/quick-silver-preview-3](url)

- please fix it so that in landscape the user can switch to other tools. i can't switch to other functions like unit converter etc and vice versa.

![IMG_20240120_080418](https://github.com/sadellie/unitto/assets/65159908/872a97c5-915f-46eb-9d83-a22e5504c1cb)

![IMG_20240120_080204](https://github.com/sadellie/unitto/assets/65159908/56818c29-e57e-4e3f-9928-e3017aaa1ead)

- add preview of results in landscape mode for calculator

- fix (sometimes) app crashes when using "currency" unit converter when offline

- switching to the unit converter always caused the app to crash immediately. after using the "fuel" unit converter.

![IMG_20240120_232126](https://github.com/sadellie/unitto/assets/65159908/94e4aca8-3ab4-47d2-a9fa-4fba259830e9)

- added custom font options by selecting font files from storage, 1 by 1 or more by choice into the app. (do not use default font from android system (root))

- makes the history in the calculator editable like a "time zone" (copy and delete option) and the option can individually select the items to be deleted.

- in the calculator history there is the date of each usage history

- add history for "date calculator" (both) and "body mass"

- a click/tap on the mini navigation bar icon triggers the calculator to display the history, another click on the mini navigation bar icon can close the history, so it's not just dragging it up and down

- add a new built-in app feature, even if the phone's auto-orientation setting is off. The app can detect when the phone is tilted to landscape and display an icon (will disappear if ignored for a moment), if tapped as the user wishes the app will change to landscape orientation, so the orientation does not automatically change after tilting. This also applies when doing the opposite, from landscape to portrait.

**Comment by Ananas-Kuchen** [comment]
- please turn off the dynamic color by default

- suggestion to add font files, there is a special page to manage font files and an option to delete font files that have been added by users.

**Comment by sadellie** [comment]
# Landscape layout
You can swipe from edge. Top bar is hidden when there is not enough space for it.

If you use gesture navigation - hold left for a second and then drag it (this way gesture navigation will not get triggered).

# Preview in landscape mode
Same thing. Currently no plans on changing this behavior. Landscape mode on phone is the least prioritized.

# Unit converter crashes
Fixed in #167 

# Custom fonts
Not planned. This will conflict with other planned features.

# Calculator history improvements
Planned, but waiting for Google to add necessary features in libraries so that I don't reinvent the wheel.

# History in Date calculator and Body mass
Planned, currently prototyping.

# Opening calculator history with a button
Maybe.

# Auto-rotate
Currently no plans on ignoring device settings (vibrations, rotation, screen timeout and etc.). 

Also, i think the feature you have described is already implemented in new Android versions. You should ask you OS developer to add/enable it.

# Dynamic theme by default
Not planned. Why do you want it to be turned off?

**Comment by Ananas-Kuchen** [comment]
> # Landscape layout
> You can swipe from edge. Top bar is hidden when there is not enough space for it.
> 
> If you use gesture navigation - hold left edge for a second and then drag it (this way gesture navigation will not get triggered).
> 

While borrowing the phone, I didn't realize it (just borrowed it again and yes, it works). my own phone supports gesture and edge, but since screen touch is dead in some areas including the top screen now I can't use these features properly, I even have to use another launcher to be able to pull up notifications by swiping on the accessible screen. previous versions of the unitto in landscape mode had a top bar button, so I'm surprised that when it was updated, it wasn't there (maybe you could add it in the settings, giving users the option to use a button/edge for the top bar?)

> # Opening calculator history with a button
> Maybe.

😁

> # Auto-rotate
> Currently no plans on ignoring device settings (vibrations, rotation, screen timeout and etc.).
> 
> Also, i think the feature you have described is already implemented in new Android versions. You should ask you OS developer to add/enable it.

well, I realized the button that appears to manually change the orientation if tilting the phone is available like in android 11 (borrowed phone). that's why I asked the app to have that feature since my phone is stuck on an old android version (if possible?)

> # Dynamic theme by default
> Not planned. Why do you want it to be turned off?

I like the default theme (green you set), and sometimes using a dark theme / with amoled is good. because when the dynamic theme is on by default it will change to another color (not my favorite) adjusting the changed wallpaper
