### ISSUE TITLE
update currencies when network becomes available

### ISSUE THREAD

**Issue by alekksander** [sadellie/unitto#31]
Please consider automatically updating currencies when network bocomes available again. I'm currently traveling around Europe and reception in smaller places or behind buildings is often lost. If in this time I need to use unitto (which is more often than I'd imagine, but since the issue I'm back to calculator) values are not stored per 24h/12h/6h period nor updated once reception is back. This is frustrating and can be fixed only by closing and reopening application again — only then it attempts to download currencies again. Should either download them only on first run and update per specific period of time or reattempt when connection is available. Thanks!

**Comment by fellinir** [comment]
Can you also please insert a setting/variable to choose the frequency of FX rates updates?
Meaning, do not be obliged to update every time the app opens and network is on, but allow some age, let's say 1 hour. If within that hour I open the app multiple times then do not let the app download the rates every time.
Another idea: implement a refresh button when converting currencies, so that the user will be able to manually refresh the rates, if not satisfied by the aged one and he wishes so (like even 1 hour old).

**Comment by sadellie** [comment]
@fellinir 
> Can you also please insert a setting/variable to choose the frequency of FX rates updates? Meaning, do not be obliged to update every time the app opens and network is on, but allow some age, let's say 1 hour. 

Unitto doesn't work this way at all. Currency rates are updated every time "left unit" (the one from "Convert from" screen) changes. 
Currency rates come from https://github.com/fawazahmed0/currency-api, where rates are updated daily, changing update period is not possible.

> If within that hour I open the app multiple times then do not let the app download the rates every time. Another idea: implement a refresh button when converting currencies, so that the user will be able to manually refresh the rates, if not satisfied by the aged one and he wishes so (like even 1 hour old), and display the timestamp of latest refresh.

Working with "aged" is not a planned feature. Unitto uses latest available data only.
