### ISSUE TITLE
Bug on opening

### ISSUE THREAD

**Issue by BabyOilJohnson** [sadellie/unitto#92]
As title mentioned
Version: nadeshiko-pink-preview-1

https://github.com/sadellie/unitto/assets/101601874/ed07eed8-4f27-4e7c-9fde-6c9a1360eae4

**Comment by sadellie** [comment]
I don't see anything wrong here. Do you mean the loading state for the keyboard?

**Comment by BabyOilJohnson** [comment]
Do you mean the loading state for the keyboard?

Yeah, I think so. It wasn't in the stable version.

**Comment by sadellie** [comment]
It's a fix for #89.

The UI loads faster than preferences for calculator (formatting, haptic feedback, zero button position).

In previous releases [default settings](https://github.com/sadellie/unitto/blob/9288f19f6dc8136684122555ea268db7269e1cb4/data/userprefs/src/main/java/com/sadellie/unitto/data/userprefs/UserPreferences.kt#L86-L94C2) were initially applied in that case. No one didn't notice it because preferences (formatting) load faster than you start typing. With the addition of "Middle zero" option this issue became visible.

There are 2 options for fixing it:
1. Delay drawing the UI (show blank screen)
2. Show initial state to indicate loading

I choose showing initial state. Maybe I will change it to showing blank page for a couple of frames if too many people find it confusing.

P.S. preferences for the app theme load separately, that's why the app can load a proper theme even though other preferences are not loaded yet

**Comment by krishna8755** [comment]
I also have this bug
